ThePrimeagen/ts-rust-zig-deez

- build.zig
- src/lexer/lexer.zig
- src/main.zig
also, don't cache tests which can be confusing.
> build: enable $zig build test + lexer Token.Tag

- src/lexer/lexer.zig
> zig lexer: keywords ComptimeStringMap + std.ascii

- csharp/lexer.tests/LexerTest.cs
- csharp/lexer/Lexer.cs
- csharp/lexer/Program.cs
- csharp/lexer/Tokens.cs
This PR adds lexer for multiple chars instead of only single chars like before
> C# Implementing parsing for multiple chars

- .github/LANG_TEMPLATE/.gitignore
- .github/LANG_TEMPLATE/Dockerfile
- .github/LANG_TEMPLATE/Makefile
- .github/LANG_TEMPLATE/make.cmd
- README.md
Added a folder .github/LANG_TEMPLATE for super easy creation of new implementations. It contains:
```bash
├── .gitignore   # for all editor-specific or os-specific files, add additional stuff for your language
├── Dockerfile  # for Docker builds
├── Makefile     # convenient commands runner (make <cmd>) under *NIX systems
└── make.cmd  # convenient commands runner (.\make.cmd <cmd>) under Windows
```
And also added a simple README.md file, with brief explanations on what's what.
> DevOps-ish Update

- fsharp/Lexer/Program.fs
Inspired by @tjdevries OCaml implementation
> refactor(fsharp): use readWhile for reading multiple characters

- bash/.gitignore
- bash/Dockerfile
- bash/Makefile
- bash/make.cmd
- bash/src/lexer.sh
- bash/src/lexer_test.sh
slightly cursed (`"${ret#"${ret%%[![:space:]]*}"}"`)
> Add lexer for bash implementation

- CODEOWNERS
Completed chapter 1 in D lang for PR #63, so I figured I should take the mantle in a separate pull request.
> add self to CODEOWNERS

- swift/lexer.swift
- swift/lexer_tests.swift
- swift/token.swift
> Add Swift version

- vlang/lexer.v
- vlang/lexer_test.v
- vlang/main.v
- vlang/tokens.v
> added a V lang interpreter

- roc/src/Eval.roc
- roc/src/Lexer.roc
- roc/src/Parser.roc
The first version was my personal version that was messing around with Data Oriented Design and other hacks.
This version is way cleaner, easier to follow, and more idiomatic.
Should be much closer, to other functional languages.
> make Roc implementation way simpler and more idiomatic

- bash/lexer
- bash/lexer_test
- lua/.gitignore
- lua/Dockerfile
- lua/Makefile
- lua/lexer/lexer.lua
- lua/lexer/lexer_test.lua
- lua/make.cmd
- lua/stylua.toml
Lua lexer added. This works fairly well. I will update Dockerfile and Makefile later. Bash lexer added too, but still not tested well.
> Added Lua and Bash Lexer

- odin/lexer/lexer.odin
Small improvement to the Odin code.
I believe this better showcases Odin's capabilities by making better use of the switch-case construct. I also removed a few procedures (`number`, `keyword`, `ident`), as I feel the code is rather simple and thus we don't really need to abstract it away (we can add them back if complexity increases later), we also improve readability by keeping all `append(&l.tokens, ...)` calls to a single place (the `scan_token` procedure).
Hopefully you can agree with me :)
> Refactor Odin lexer

- cobol/README.md
- cobol/lexer-data.cpy
- cobol/lexer-proc.cpy
- cobol/tests.cbl
- cobol/token-data.cpy
i should be sleeeping rn instead of doing this ;_;
i really shouldn't do it but i probably will be tempted to continue implementing the full lexer 😔
> feat(cobol): COBOL deez nuts (only single char tokens)

- CODEOWNERS
- scala/.gitignore
- scala/.scalafmt.conf
- scala/Dockerfile
- scala/Makefile
- scala/lexer.scala
- scala/lexer.test.scala
- scala/make.cmd
Scala 3 implementation containing
> Add Scala implementation

- prolog/.gitignore
- prolog/Dockerfile
- prolog/Makefile
- prolog/make.cmd
- prolog/src/lexer.pl
- prolog/src/main.pl
Haskek implementation already taken, so I had to go deeper.
Prolong my suffering
> Add prolog implementation

- fortran/.dockerignore
- fortran/.gitignore
- fortran/Dockerfile
- fortran/Makefile
- fortran/ast.f90
- fortran/lexer.f90
- fortran/list.f90
- fortran/parser.f90
- fortran/repl.f90
- fortran/test_ast.f90
- fortran/test_lexer.f90
- fortran/test_parser.f90
- fortran/token.f90
I heard you guys like them di** big & girthy so here it is
> Chapter 2 in Fortran

- java/Lexer.java
- java/Tests.java
- java/TokenType.java
Improving the Java solution by using more modern features (returning from switch, Optional, multi line String, type inference) and native Character methods.
Both tests still pass.
> Improving the Java solution

- nim/.gitignore
- nim/src/lexer.nim
- nim/tests/test.nim
This PR has two small changes.
First I removed the testing code from `lexer.nim` because it already exists in the `tests` directory.
Second I made minor but easy changes to the text to bring it closer to the public style guides.
> Nim changes

- nim/src/lexer.nim
- nim/tests/test.nim
Cleaned up the code a bit and made it nicer to use/look at.
All of my changes were made while referencing 3 alternative nim implementations (jakelsen, lantos1618, and mine).
We probably need to overhaul the lexer to be much closer to what the book does because there are details that were carefully planed for future use that got discarded. Tests still work of course.
> More changes to the lexer

- fsharp/Monkey/Lexer.fs
- fsharp/Monkey/Lexer.fsi
Makes the code more "functional" F# code as opposed to a direct implementation of the interpreter book
> refactor(fsharp) Remove mutations

- CODEOWNERS
- go-concurrent/Dockerfile
- go-concurrent/Makefile
- go-concurrent/go.mod
- go-concurrent/lexer/lexer.go
- go-concurrent/lexer/lexer_test.go
- go-concurrent/main.go
I wrote this based on this talk [Lexical Scanning in Go](https://www.youtube.com/watch?v=HxaD_trXwRE) by Rob Pike, where he
implements a concurrent lexer for golang templates.
> Go - Concurrent lexer based on Rob Pike's talk

- CODEOWNERS
With the approval of @ThePrimeagen and @marcusziade
> Added extra codeowner for Swift

- groovy/Repl.groovy
added a basic ass repl that just lists tokens for now
> groovy - add basic repl

- roc/Makefile
- roc/README.md
- roc/src/Eval.roc
- roc/src/Parser.roc
- roc/src/Repl.roc
Some cleanup. Fix the actual evaluator and repl. Add a make file. Link to where the nightly can be downloaded.
> More Roc updates

- CODEOWNERS
- gdscript/.gitignore
- gdscript/Dockerfile
- gdscript/Makefile
- gdscript/project.godot
- gdscript/src/lexer/Lexer.gd
- gdscript/src/lexer/Token.gd
- gdscript/src/main.gd
- gdscript/test/lexer_tests.gd
Implemented the lexer at the moment, the rest is on its way (maybe)
> Add GDScript implementation

- R5RS/src/ast.rkt
- R5RS/src/eval.rkt
- R5RS/src/lexer.rkt
- R5RS/src/object.rkt
- R5RS/src/parser.rkt
- R5RS/src/token.rkt
- R5RS/src/utils.rkt
- R5RS/tests/eval_test.rkt
- R5RS/tests/lexer_test.rkt
- R5RS/tests/object_test.rkt
- R5RS/tests/parser_test.rkt
- R5RS/tests/test.rkt
This completed the book.
Features a (terrible) implementation of the fnv hashing algorithm in pure R5RS 😎
> R5RS finished

- clj/.dockerignore
- clj/.vscode/settings.json
- clj/Dockerfile
This PR exists only for the purpose for push my change to the ThePrimeagen/ts-rust-zig-deez repository. Everyone else you want to contribute can submit PR to my fork [here](https://github.com/Vikasg7/ts-rust-zig-deez) so that we don't clutter PRs in ThePrimeagen repo.
> Clojure Maintenance PR as CODEOWNER

- go-concurrent/lexer/lexer.go
- go-concurrent/lexer/lexer_test.go
- go-concurrent/main.go
commit 8d3734199086241037440f1065b520a24ce2884f
Author: Amis Shokoohi <amisshokoohi@gmail.com>
Date:   Tue Jun 6 17:33:48 2023 +0000
Add more tokens
commit e0e42904f71278d0e1a3fe0f731a2cbba1658d67
Author: Amis Shokoohi <amisshokoohi@gmail.com>
Date:   Mon Jun 5 20:18:56 2023 +0000
Rename brace to squirly
> Extend the go-concurrent lexer

- cpp-spongman/CMakeLists.txt
- cpp-spongman/Makefile
- cpp-spongman/prelude
- cpp-spongman/src/lexer/lexer.cc
- cpp-spongman/src/lexer/token.cpp
- cpp-spongman/src/lexer/token.hpp
- cpp-spongman/src/parser/builtins.cpp
- cpp-spongman/src/parser/builtins.hpp
- cpp-spongman/src/parser/expression.cpp
- cpp-spongman/src/parser/expression.hpp
- cpp-spongman/src/parser/program.cpp
- cpp-spongman/src/parser/statement.cpp
- cpp-spongman/src/parser/value.cpp
- cpp-spongman/src/parser/value.hpp
- cpp-spongman/tests/lexer_test.cpp
- cpp-spongman/tests/parser_test.cpp
> c++ : hashes, puts. all done.

- CODEOWNERS
- k/.gitignore
- k/Dockerfile
- k/Makefile
- k/lexer.k
- k/test.k
pretty sure this docker file won't run lmao
will add a state machine impl some time later, maybe
> add k lexer impl

- swift/Sources/Lexer/lexer.swift
- swift/Sources/Lexer/token.swift
Refactor the lexer to make use of Swift's extension feature, and moved to Swift associated enums
> Refactoring the Swift Lexer

- java/monkey/src/main/java/TokenType.java
Optional should not be used as parameters & return type.
> Should not use Optional as field.

- cpp-spongman/CMakeLists.txt
- cpp-spongman/Makefile
- cpp-spongman/README.md
- cpp-spongman/src/lexer/lexer.hh
- cpp-spongman/src/main.cpp
- cpp-spongman/src/parser/builtins.cpp
- cpp-spongman/src/parser/builtins.hpp
- cpp-spongman/src/parser/environment.cpp
- cpp-spongman/src/parser/environment.hpp
- cpp-spongman/src/parser/expression.cpp
- cpp-spongman/src/parser/program.cpp
- cpp-spongman/src/parser/statement.cpp
- cpp-spongman/src/parser/statement.hpp
- cpp-spongman/src/parser/utils.hpp
- cpp-spongman/src/parser/value.cpp
- cpp-spongman/src/parser/value.hpp
- cpp-spongman/tests/parser_test.cpp
- more Makefile targets
- cleanup Value equality, add 'as', 'is' helpers
- use ordered-map for environment
- more README
- char Array printing
> c++: various cleanup

- prolog2/lib/evaluator.pl
- prolog2/lib/lexer.pl
- prolog2/lib/parser.pl
- prolog2/repl.pl
- prolog2/test.pl
Hello,
I added the parser and the evaluator to the prolog2 implementation.
> add parser and evaluator (no error handling) to prolog2
